Table fct_results {
  event_id string
  athlete_id string
  athlete_performance float
  athlete_age_category string
  athlete_average_speed float
  year_of_event integer
  event_unit string
}

Table dim_event {
  event_id string [primary key, ref:< fct_results.event_id]
  event_name string
  event_type string
  event_country string
  event_distance_length double
  event_number_of_finishers integer
  event_dates date
}

Table dim_athlete {
  athlete_id string [primary key, ref:< fct_results.athlete_id]
  athlete_gender string
  athlete_club string
  athlete_country string
  athlete_year_of_birth integer
}